### ISSUE TITLE
Whatsapp window display issue

### ISSUE THREAD

**Issue by wychris85** [dikalo/ahome-desk-issues#11]
Whatsapp Window rendering issue.
![image](https://cloud.githubusercontent.com/assets/15270431/14961589/a97cd486-109a-11e6-9827-a28282b903ec.png)

**Comment by wychris85** [comment]
only a small part of the window is displayed. I have to scroll til the bottom see all the content. I can observe the same issue in the whatsapp chat window.
![image](https://cloud.githubusercontent.com/assets/15270431/14961634/d13d9c4e-109a-11e6-9c3b-006f55b18bbf.png)

**Comment by eemi2010** [comment]
Fixed.
