### ISSUE TITLE
Gateway- gmx

### ISSUE THREAD

**Issue by elahome** [dikalo/ahome-desk-issues#12]
gmx aufrufen mit http geht nicht
das Scrollen nach unten mit dem Scroll bar geht nicht
nach dem Login in gmx übernimmt gmx das ganze Fenster und schmeisst  de Desk raus.
mann muss https://desk.ahome-it.com/ neu aufrufen und sich anmelden.
dann kommt die Meldung 
![image](https://cloud.githubusercontent.com/assets/8964615/14981473/c5537d82-112f-11e6-8c07-6f8932b3d7cc.png)

**Comment by eemi2010** [comment]
Fixed now.
