### ISSUE TITLE
chrome-extension message

### ISSUE THREAD

**Issue by elahome** [dikalo/ahome-desk-issues#3]
![chrome-extension](https://cloud.githubusercontent.com/assets/8964615/14930451/4af87790-0e64-11e6-83bd-cbdcf5e52c3d.JPG)

this marked message (see image) could prevent users from downloading the extension. Change if possible

**Comment by eemi2010** [comment]
### Permissions

The message shown by Google Chrome for the requested permissions is far from the real needs of the extension, but the permissions are technically required for the following reasons:

**• Read and change your data :** Required to drop x-frame-headers on each request.

**• Read your browsing history:** Required to detect whether an active ahome desk session exist and eventually display a new page.
