### ISSUE TITLE
Dropbox API (oauth2) issue

### ISSUE THREAD

**Issue by baldram** [dikalo/ahome-desk-issues#6]
In 90% of tries I couldn't connect to Dropbox getting error: 

> Error (400) It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.

and below "more details for developers":

> Invalid redirect_uri. It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).

The app tries to connect to https://www.dropbox.com/1/oauth2/authorize?client_id=... 

Then finally I was lucky and login screen showed up. 
Unfortunatelly then I got the error as below:

> This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.

Next try (I logged out, logged in to Ahome-desk) I started to get Error 400 again...

System: Mint Linux; Chrome browser, but I tried also under Windows and Chrome.

**Comment by eemi2010** [comment]
Yeah. Production status is actually pending at dropbox. We hope this will be granted soon. Sorry for the delay.

**Comment by eemi2010** [comment]
We did not expect so many people using the app at the same time. Sorry for that.

**Comment by eemi2010** [comment]
Should be fixed now. Please try again.

**Comment by baldram** [comment]
It worked! :+1: Dropbox drive connected.

**Comment by eemi2010** [comment]
Thx for trying. We are still ate the beginning of what we want to there. LOOOOTS of features coming soon. And  if you any suggestion/critic/wish please let us know.
